In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [2]:
df = pd.read_csv("data/train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df_cls = df.drop(["PassengerId","Name","Ticket","Cabin","SibSp","Parch","Embarked"],axis=1,errors="ignore")
df_cls.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
df_cls["Sex"] = df_cls["Sex"].astype("category").cat.codes
df_cls.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [5]:
df_cls.info()
df_cls.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int8   
 3   Age       714 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(2), int8(1)
memory usage: 28.8 KB


Survived      Pclass         Sex         Age        Fare
count  891.000000  891.000000  891.000000  714.000000  891.000000
mean     0.383838    2.308642    0.647587   29.699118   32.204208
std      0.486592    0.836071    0.477990   14.526497   49.693429
min      0.000000    1.000000    0.000000    0.420000    0.000000
25%      0.000000    2.000000    0.000000   20.125000    7.910400
50%      0.000000    3.000000    1.000000   28.000000   14.454200
75%      1.000000    3.000000    1.000000   38.000000   31.000000
max      1.000000    3.000000    1.000000   80.000000  512.329200

In [6]:
df_cls.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [7]:
df_cls["Age"] = df_cls["Age"].fillna(df_cls["Age"].mean()).astype("int")

In [8]:
df_cls[df_cls["Age"].isnull()]

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, Fare]
Index: []

In [9]:
df_rescaled = df_cls
df_rescaled.head()

Survived  Pclass  Sex  Age     Fare
0         0       3    1   22   7.2500
1         1       1    0   38  71.2833
2         1       3    0   26   7.9250
3         1       1    0   35  53.1000
4         0       3    1   35   8.0500

In [10]:
for i in range(df_rescaled.shape[1]):
    mean = df_rescaled.iloc[:, i].mean()
    max_ = df_rescaled.iloc[:, i].max()
    min_ = df_rescaled.iloc[:, i].min()
    if max_ != min_:
        df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
    else:
        df_rescaled.iloc[:,i]= 0
df_rescaled.head()

C:\Users\simoo\AppData\Local\Temp\ipykernel_15744\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0     -0.383838
1      0.616162
2      0.616162
3      0.616162
4     -0.383838
         ...   
886   -0.383838
887    0.616162
888   -0.383838
889    0.616162
890   -0.383838
Name: Survived, Length: 891, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
C:\Users\simoo\AppData\Local\Temp\ipykernel_15744\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      0.345679
1     -0.654321
2      0.345679
3     -0.654321
4      0.345679
         ...   
886   -0.154321
887   -0.654321
888    0.345679
889   -0.654321
890    0.345679
Name: Pclass, Length: 891, dtype: float64' has dtype incompatible with in

Survived    Pclass       Sex       Age      Fare
0 -0.383838  0.345679  0.352413 -0.094304 -0.048707
1  0.616162 -0.654321 -0.647587  0.105696  0.076277
2  0.616162  0.345679 -0.647587 -0.044304 -0.047390
3  0.616162 -0.654321 -0.647587  0.068196  0.040786
4 -0.383838  0.345679  0.352413  0.068196 -0.047146

In [11]:
df_cls.head()

Survived    Pclass       Sex       Age      Fare
0 -0.383838  0.345679  0.352413 -0.094304 -0.048707
1  0.616162 -0.654321 -0.647587  0.105696  0.076277
2  0.616162  0.345679 -0.647587 -0.044304 -0.047390
3  0.616162 -0.654321 -0.647587  0.068196  0.040786
4 -0.383838  0.345679  0.352413  0.068196 -0.047146

In [12]:
X = df_cls.iloc[:,1:]
Y = df_cls.iloc[:,0]

x = X.to_numpy()
y = Y.to_numpy()
print("=" * 50)
print(x[:10])
print("=" * 50)
print(y[:10])
print(x.shape)
print(y.shape)
print("=" * 50)

[[ 0.34567901  0.35241302 -0.09430415 -0.04870737]
 [-0.65432099 -0.64758698  0.10569585  0.07627731]
 [ 0.34567901 -0.64758698 -0.04430415 -0.04738986]
 [-0.65432099 -0.64758698  0.06819585  0.04078587]
 [ 0.34567901  0.35241302  0.06819585 -0.04714587]
 [ 0.34567901  0.35241302 -0.00680415 -0.04634893]
 [-0.65432099  0.35241302  0.30569585  0.03837043]
 [ 0.34567901  0.35241302 -0.34430415 -0.02172277]
 [ 0.34567901 -0.64758698 -0.03180415 -0.04112767]
 [-0.15432099 -0.64758698 -0.19430415 -0.00416414]]
[-0.38383838  0.61616162  0.61616162  0.61616162 -0.38383838 -0.38383838
 -0.38383838 -0.38383838  0.61616162  0.61616162]
(891, 4)
(891,)


In [15]:
import tensorflow as tf
y = (y >= 0.5).astype(int)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=4, activation="relu"),
    tf.keras.layers.Dense(units=1, activation="sigmoid")
])

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"]
)

model.fit(x, y, epochs=100)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.7643 - loss: 0.6495
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7969 - loss: 0.6336
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7890 - loss: 0.6187
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7868 - loss: 0.6041
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7868 - loss: 0.5904
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7868 - loss: 0.5773
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7868 - loss: 0.5650
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7868 - loss: 0.5538
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7868 - loss: 0.5435
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7868 - loss: 0.5339
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7868 - loss: 0.5253
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step